body:
  - type: textarea
    attributes:
      label: Enter your post
    validations:
      required: True
  - type: checkboxes
    attributes:
      label: Check this box if you want an AI-generated answer as a first response.
      options:
        - label: I want an AI-generated answer as a first response.
  
